### ISSUE TITLE
Clap grep with query does not start searching immediately

### ISSUE THREAD

**Issue by bartlibert** [liuchengxu/vim-clap#515] opened 2020-09-03 08:27 UTC
**Environment (please complete the following information):**
 - OS: Windows 10
 - (Neo)Vim version: vim 8.2.1563
 - vim-clap version: 973ebcf
 - Have you reproduced with a minimal vimrc: yes
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: yes

**Describe the bug**
When I use `:Clap grep ++query=something`, the grep window pops up, with "something" prepopulated, but the search does not start until I type something extra in the window (e.g. space character). This is inconvenient because I use some "grep for word under cursor" and "grep for last search" shortcuts.

**Clap debug**

```

            has cargo: 1
            has maple: C:\Users\BL\_yadm\.vim\pack\minpac\start\vim-clap/target/release/maple.exe
           maple info: version 0.1.20, built for x86_64-pc-windows-msvc by rustc 1.44.1 (c7087fe00 2020-06-17).

         has +python3: 1
has py dynamic module: 1
     Current FileType: 
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = 'C:\Users\BL\_yadm\.vim\pack\minpac\start\vim-clap\autoload'
    let g:clap#popup#display = {'shrink': function('51'), 'open': function('<SNR>28_create_display'), 'width': 274, 'shrink_if_undersize': function('50')}
    let g:clap#popup#preview = {'line_count': function('<SNR>27__line_count'), 'show': function('52'), 'hide': function('53'), 'bufnr': 3, 'add_highlight': function('54'), 'get_lines': function('<SNR>27__get_lines'), 'getbufvar': function('<SNR>27__getbufvar'), 'setbufvar_batch': function('<SNR>27__setbufvar_batch'), 'setbufvar': function('<SNR>27__setbufvar'), 'winid': 1002, 'win_is_valid': function('<SNR>27__win_is_valid'), 'goto_win': function('<SNR>27__goto_win'), 'set_syntax': function('55')}
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 0
    let g:clap_forerunner_status_sign = {'done': '¿', 'running': '!', 'using_cache': '*'}
    let g:clap_indicator_winid = 1003
    let g:clap_insert_mode_only = v:false
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['¶', '´'], 'arrow': ['²', '°']}
    let g:clap_spinner_winid = 1005
  Provider Variables:
    let g:clap_provider_yanks_max_entries = 100
```

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```

2. Start (neo)vim with command: `vim -u min.vim`

3. Type ':Clap grep ++query=something'

4. See error: popup is opened with "something" populated, but searching does not occur

**Expected behavior**
The clap grep popup opens with the "something" text inside and immediately starts searching for something

**Additional context**
It used to work until revision 387eff6b0b05267bda8c38cd5004311e33a47cd1

**Comment by liuchengxu** [comment] 2020-09-03 10:28
Can't reproduce. Both `:Clap grep ++query=foo` and `:Clap grep2 ++queyr=foo` works for me. You might have some misunderstanding here.

**Comment by bartlibert** [comment] 2020-09-03 12:15
I'm probably misunderstanding then, but your comment does not help me understand it better. 

Do you mean that when you type ":Clap grep ++query=foo" you immediately get results for "foo"? Or do you mean I don't understand how it should work and this is expected behaviour?
I'm not using cache BTW.

**Comment by liuchengxu** [comment] 2020-09-03 12:25
>Do you mean that when you type ":Clap grep ++query=foo" you immediately get results for "foo"?

Yes, I also often search the word under the cursor, works great for me. BTW the `grep2` provider is recommended, which is much responsive the `grep` provider.

**Comment by bartlibert** [comment] 2020-09-03 12:26
grep2 has the same issue. But I'll debug it myself then...

Op do 3 sep. 2020 om 14:25 schreef Liu-Cheng Xu <notifications@github.com>:

**Comment by bartlibert** [comment] 2020-09-03 13:48
I've looked around a bit, but I'm a bit stuck (and out of time) now, just leaving this here if you might have some input (and as a log of my investigation, if you don't like this, feel free to delete this)

The flow starts with a call to `clap#for`: 
https://github.com/liuchengxu/vim-clap/blob/973ebcf5411eea777450673b0b3f132beb5004d7/autoload/clap.vim#L381

This gets us to this part in the code:
https://github.com/liuchengxu/vim-clap/blob/973ebcf5411eea777450673b0b3f132beb5004d7/autoload/clap.vim#L297-L299

At this point, `g:__clap_open_win_pre` is set to true. Then the `open_win` call gets us to `clap#popup#open`:

https://github.com/liuchengxu/vim-clap/blob/973ebcf5411eea777450673b0b3f132beb5004d7/autoload/clap/popup.vim#L331-L357

Here `apply_query` is called

https://github.com/liuchengxu/vim-clap/blob/973ebcf5411eea777450673b0b3f132beb5004d7/autoload/clap/api.vim#L415-L427

This finally calls the provider function `on_typed`:
https://github.com/liuchengxu/vim-clap/blob/973ebcf5411eea777450673b0b3f132beb5004d7/autoload/clap/api.vim#L362-L374

In this function, the value of `g:__clap_open_win_pre` is checked. Because this is `v:true` (I checked this), the function returns and the query is never performed. If I remove the check, it works as expected (but I'm not fully sure why the check is there, but it's probably for a very good reason ;) )

Todo: find out why this is the flow we follow and why everything fails...

**Comment by liuchengxu** [comment] 2020-09-04 00:24
The reason for `g:__clap_open_win_pre` is in the comments: https://github.com/liuchengxu/vim-clap/blob/973ebcf5411eea777450673b0b3f132beb5004d7/autoload/clap.vim#L289-L297

Maybe you can see if this patch works for you:

```diff
diff --git a/autoload/clap/api.vim b/autoload/clap/api.vim
index 204e1a5..cd41b68 100644
--- a/autoload/clap/api.vim
+++ b/autoload/clap/api.vim
@@ -360,7 +360,7 @@ function! s:init_provider() abort

   " After you have typed something
   function! provider.on_typed() abort
-    if get(g:, '__clap_open_win_pre', v:false)
+    if get(g:, '__clap_open_win_pre', v:false) && !has_key(g:clap.context, 'query')
       return
     endif
     try
```

**Comment by bartlibert** [comment] 2020-09-04 05:51
I should have put it differently: I read the comment, but I did not fully
understand it ;)

The patch fixes the issue for me!

Op vr 4 sep. 2020 om 02:24 schreef Liu-Cheng Xu <notifications@github.com>:

**Comment by liuchengxu** [comment] 2020-09-04 06:39
Great, the patch has been merged into the master.

**Closed** 2020-09-04 06:39 UTC
Labels: can-not-reproduce
