### ISSUE TITLE
Preview window overlap with file list window in neovim-0.5

### ISSUE THREAD

**Issue by ray-x** [liuchengxu/vim-clap#454] opened 2020-06-04 04:51 UTC
**Environment (please complete the following information):**
 - OS: Mac
 - (Neo)Vim version: Neovim-0.5 (--HEAD)
 - vim-clap version: latest

**Describe the bug**
In neovim, float window seems to be flexible and  preview could overlap list window (please see attached image) The selected is hidden when  I move cursor down. 

**To Reproduce**
Install both neovim-0.4.3 and neovim-0.5.  Same configure but neovim 0.5 does not work correctly.

**Expected behavior**
neovim-0.5 should behave same as neovim-0.4.3

**Screenshots**
begin search and move cursor to last item in list:
![Screen Shot 2020-06-04 at 2 34 53 pm](https://user-images.githubusercontent.com/1681295/83716167-7c4b1780-a672-11ea-8b4b-0a86aab8876c.png)

continue move with `down`, cursor is gone from search list and I can see highlight move in preview list(highlighted):
![Screen Shot 2020-06-04 at 2 37 23 pm](https://user-images.githubusercontent.com/1681295/83716192-8cfb8d80-a672-11ea-8eb8-3da07c4edf43.png)

Continue move with down:
![Screen Shot 2020-06-04 at 2 37 32 pm](https://user-images.githubusercontent.com/1681295/83716200-92f16e80-a672-11ea-8741-8a994d60ef1a.png)

Also, The search result list window size seem to change with cursor movement, in previous screen shot, list is 3 items(fixed), in the screen shot, it grow to 12.
![Screen Shot 2020-06-04 at 2 36 27 pm](https://user-images.githubusercontent.com/1681295/83716217-9dac0380-a672-11ea-98fc-07ab02ac15ab.png)

**Additional context**

**Comment by liuchengxu** [comment] 2020-06-04 05:12
- I don't want to spend time debugging the unstable neovim version.
- vim-clap has a cache feature which will load the lines lazily. If you keep moving the cursor down, and the cache has more lines, these cached lines will be loaded then. `:Clap grep` has a new versin `:Clap grep2`, you can try that too.

**Comment by ray-x** [comment] 2020-06-04 05:22
Thanks for your suggestions, I will use grep2 more.
Also, for this defect, `:Clap grep2` also has similar issue.

**Comment by liuchengxu** [comment] 2020-06-04 05:49
I upgraded my neovim to HEAD-96568d5, still can't reproduce it.

**Comment by ray-x** [comment] 2020-06-05 06:31
I think I could reproduce it now. (even with neovim 0.4.3). Using default config but shrink the terminal size so that height+preview is greater than what was remaining in the terminal screen.
Also, FYI, the setup only breaks neovim, macvim works fine.

My clap debug log
```

            has cargo: 1
            has maple: /Users/ray.xu/.vim/plugged/vim-clap/target/release/maple
           maple info: version 0.1.17, built for x86_64-apple-darwin by rustc 1.43.1 (8d69840ab 2020-05-04).

         has +python3: 1
has py dynamic module: 0
     Current FileType: startify
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/Users/ray.xu/.vim/plugged/vim-clap/autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_current_selection_sign = {'texthl': 'ClapCurrentSelectionSign', 'linehl': 'ClapCurrentSelection', 'text': ''}
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_icon = 1
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_insert_mode_only = v:false
    let g:clap_layout = {'col': '17%', 'row': '33%', 'width': '67%', 'relative': 'win', 'height': '33%'}
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'curve'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
    let g:clap_selected_sign = {'texthl': 'ClapSelectedSign', 'linehl': 'ClapSelected', 'text': ''}
    let g:clap_theme = 'material_design_dark'
  Provider Variables:
                     []
```

A recored gif:

![nvim](https://user-images.githubusercontent.com/1681295/83844188-d36feb80-a749-11ea-8abf-1f03e793f80c.gif)

**Comment by liuchengxu** [comment] 2020-06-05 08:10
You can close and reopen clap, or set `g:clap_layout` and `g:clap_preview_size` to fit your terminal size.

**Comment by ray-x** [comment] 2020-06-05 13:27
1) Close and reopen does not help. the clap_layout and clap_preview_size was setup in init.vim.  When the console windows size decreased small enough, the defect always reproduce.
2) The search result and preview overlap is not good.  In some extreme cases the preview window may fill all the space of clap window(as showed in following screen shot). This may not an issue from clap. But I think vim does much better in this area.

<img width="836" alt="Screen Shot 2020-06-05 at 9 56 09 pm" src="https://user-images.githubusercontent.com/1681295/83873599-6e32ef00-a777-11ea-9c11-a75c06524704.png">

**Comment by liuchengxu** [comment] 2020-06-05 14:38
>But I think vim does much better in this area.

Neovim's floating_win and Vim's popup are two things anyway, even they do share lots of things in common.

>When the console windows size decreased small enough, the defect always reproduce.

There is no good solution for this edge case. I won't spend lots of time thinking about the edge cases like this because I never have these issues,  and normally most people won't use a terminal having too small size. Let me know if you have a good solution, this will be a won't fix.

**Comment by liuchengxu** [comment] 2020-06-05 14:45
If you have time, you can explore how to make a fixed floating win in neovim. If you can make the preview floating window fixed, I guess it won't overtake the space of other windows.

**Closed** 2020-06-08 16:05 UTC
Labels: neovim

**Comment by ray-x** [comment] 2021-08-16 05:50
It seems this part is broken again.

clap_preview_size setup does not work when the layout is `UP`.

I use default set for `clap_layout`.

What I am suspecting is when calculate the preview height. It. does not count the border.
