### ISSUE TITLE
Specify window size

### ISSUE THREAD

**Issue by balta2ar** [liuchengxu/vim-clap#224] opened 2020-01-10 09:46 UTC
**Is your feature request related to a problem? Please describe.**
vim-clap currently uses only a part of my available screen width. Some results (e.g. filenames, tag names) are pretty long and they are cut off on the right.

**Describe the solution you'd like**
I'd like to be able to control how much screen real estate vim-clap can use. For example, I'd like to be able to all available screen width.

**Describe alternatives you've considered**
I couldn't find anything about that in the docs.

**Comment by liuchengxu** [comment] 2020-01-10 10:11
I'll consider take this issue a duplicate of #41. It's possible to achieve that by using the public api exposed by vim-clap (`:h clap-api`, the doc is still very incomplete) right now, but you have to handle the details on your own, e.g., handle the multiple windows at the same time, including the display, spinner, search text window.

Here is the quick demo of changing the display window width to the whole screen for neovim. 

```vim
function! OnEnter() abort                                                                                                                                                                     
  let opts = nvim_win_get_config(g:clap.display.winid)                                                                                                                                        
  let opts.width = &columns                                                                                                                                                                   
  call nvim_win_set_config(g:clap.display.winid, opts)                                                                                                                                        
endfunction                                                                                                                                                                                   
                                                                                                                                                                                              
autocmd User ClapOnEnter call OnEnter()   
```

But note that you have to also tweak the other floating win as well. For now, you have to rely on your own, it's not my current focus of vim-clap.

**Comment by liuchengxu** [comment] 2020-01-15 11:08
Try #240

**Comment by balta2ar** [comment] 2020-01-15 14:56
It prints the configuration to the status line, but other than that looks OK, thanks!

**Closed** 2020-01-22 02:18 UTC
Labels: feature_request
