### ISSUE TITLE
Amount of file matches missing in upper right corner

### ISSUE THREAD

**Issue by bragjo** [liuchengxu/vim-clap#567] opened 2020-10-24 15:38 UTC
_Instructions: Replace the template text and remove irrelevant text (including this line)_
**Warning: if you don't fill this issue template and provide the reproducible steps the issue could be closed directly.**

**Environment (please complete the following information):**
 - OS: Windows 10
 - (Neo)Vim version: v.0.4.3
 - vim-clap version: ???
 - Have you reproduced with a minimal vimrc: yes
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: yes 

**Describe the bug**

I'm not able to see the file matches in the vim-clap popup window inside of vim.
Also when trying to navigate into a dist folder it gives me an error message. See screenshots.

No matches found/not visualized: https://imgur.com/3dTh7De

Navigating into a dist folder: https://imgur.com/LSo95Lw

Absolute LOVE this plugin btw, I'm replacing my fzf with this one since I tend to like the graphical representation of it. it's definately a must have plugin for from now on, so good job on this one! Love it.

I would like the rest of the plugin to work though

Best regards,

J

**Comment by liuchengxu** [comment] 2020-10-24 17:03
Your screen width is just too small. Try this patch, this can be improved to use a relative value.

```diff
diff --git a/autoload/clap.vim b/autoload/clap.vim
index 70b0897..45ff7f4 100644
--- a/autoload/clap.vim
+++ b/autoload/clap.vim
@@ -51,7 +51,7 @@ let g:clap_disable_optional_async = get(g:, 'clap_disable_optional_async', v:fal
 let g:clap_no_matches_msg = get(g:, 'clap_no_matches_msg', 'NO MATCHES FOUND')
 let g:__clap_no_matches_pattern = '^'.g:clap_no_matches_msg.'$'

-let g:__clap_indicator_winwidth = 18
+let g:__clap_indicator_winwidth = 5

 let s:default_symbols = {
       \ 'arrow' : ["\ue0b2", "\ue0b0"],
```

**Comment by bragjo** [comment] 2020-10-24 17:35
@liuchengxu 

Thanks for reply.

I tried to set let g:__clap_indicator_winwidth = 5 in my vimrc without success - nothing is happening.

Best regards,

J

**Comment by liuchengxu** [comment] 2020-10-24 18:03
What's the width of your terminal?

**Comment by bragjo** [comment] 2020-10-24 18:06
> What's the width of your terminal?

tput cols: 133
tput lines: 34

**Comment by liuchengxu** [comment] 2020-10-25 00:56
Can not reproduce locally. You can try adding this debugging print:

```diff
diff --git a/autoload/clap/floating_win.vim b/autoload/clap/floating_win.vim
index 882e20f..b823082 100644
--- a/autoload/clap/floating_win.vim
+++ b/autoload/clap/floating_win.vim
@@ -190,6 +190,7 @@ function! g:clap#floating_win#spinner.shrink() abort
       if opts.width < 0
         let opts.width = 1
       endif
+      echom 'width: '.opts.width
       let g:clap#floating_win#input.width = opts.width
       call nvim_win_set_config(s:input_winid, opts)
     endif
```

**Comment by bragjo** [comment] 2020-10-25 14:34
@liuchengxu thanks, I found the issue - seems that when setting this in another plugin in my vimrc ( airline plugin ):

let g:airline_powerline_fonts = 1

it bugs out the vim-clap upper right corner, so it seems to be a font issue

**Comment by liuchengxu** [comment] 2020-10-25 15:16
Don't see how that could be related. It will be helpful if you can provide a minimal vimrc to help reproduce and find the root cause. Anyway, great to see you _solved_ it :).

**Comment by Melkster** [comment] 2020-10-27 20:22
Ran in to this issue today and also concluded that it's because of `let g:airline_powerline_fonts = 1`. The bug persists even without vim-airline installed.

This is my minimal config:

```vim
call plug#begin('~/.vim/bundle')
Plug 'liuchengxu/vim-clap', { 'do': ':Clap install-binary' }
call plug#end()

let g:airline_powerline_fonts = 1
```

**Comment by dharrigan** [comment] 2020-10-27 21:35
Hi,

I'm able to reproduce this too. With `let g:airline_powerline_fonts = 1`, I observe this:

![looks_bad](https://user-images.githubusercontent.com/427150/97364654-4403da00-189c-11eb-92af-4ff65e983e78.png)

With `let g:airline_powerline_fonts = 0`, I observe this:

![looks_good](https://user-images.githubusercontent.com/427150/97364614-38b0ae80-189c-11eb-9c34-83906629f03c.png)

-=david=-

**Comment by liuchengxu** [comment] 2020-10-29 15:55
Should be fixed in the latest master, a tricky issue..

**Closed** 2020-10-29 15:54 UTC
Labels: bug

**Comment by dharrigan** [comment] 2020-10-29 16:18
Hi!

Yup, works grand now for me :-) Thank you.
